routes/web.php
<?php

Route::get('/', 'HomeController@welcome')->middleware('lang');
Auth::routes();

Route::get('/admin-panal/login', 'Auth\AdminLoginController@showLoginForm')->name('admin-panal.login');
Route::post('/admin-panal/login', 'Auth\AdminLoginController@login')->name('admin-panal.login.submit');

Route::group(['middleware' => 'auth:admin'], function ()
{   
    Route::get('/admin-panal/contacts/data', 'ContactsContoller@anyData');
    Route::get('/admin-panal/users/data', 'UsersController@anyData');
    Route::get('/admin-panal/products/data', 'ProductsController@anyData');
    Route::get('/admin-panal/orders/data', 'OrdersController@anyData');
    
    Route::get('/admin-panal', 'AdminController@index')->name('admin-panal');

    Route::get('/admin-panal/contacts/{id}/destroy', 'ContactsContoller@destroy');
    Route::get('/admin-panal/orders/{id}/destroy', 'OrdersController@destroy');
    Route::get('/admin-panal/faqs/{id}/destroy', 'FaqsController@destroy');
    Route::get('/admin-panal/users/{id}/destroy', 'UsersController@destroy');
    Route::get('/admin-panal/colors/{id}/destroy', 'ColorsController@destroy');
    Route::get('/admin-panal/products/{id}/destroy', 'ProductsController@destroy');
    Route::get('/admin-panal/blogs/{id}/destroy', 'PostsController@destroy');
    Route::get('/admin-panal/sizes/{id}/destroy', 'SizesController@destroy');
    
    Route::get('/admin-panal/contacts/remove-all', 'ContactsContoller@RemoveAll')->name('contacts.remove-all');
    Route::get('/admin-panal/products/id/{id}/{name}/', 'ProductsController@ShowMeProduct');
    Route::get('/admin-panal/contacts/{id}/edit', 'ContactsContoller@edit');
    Route::get('/admin-panal/settings', 'SettingsController@index')->name('settings');
    Route::view('/admin-panal/settings/create', 'admin.settings.add')->name('settings.create');
    Route::post('/admin-panal/settings/create', 'SettingsController@addnewset')->name('settings.addnewset');
    Route::post('/admin-panal/settings', 'SettingsController@store');

    Route::get('/admin-panal/blogs/i/{id}/{name}', 'PostsController@ShowBlog');
    Route::get('/admin-panal/blogs/i/{id}/{name}/edit', 'PostsController@BlogEdit');
    
    Route::post('/admin-panal/users/PasswordChange', 'UsersController@updatePassword');
    Route::post('/admin-panal/users/PasswordChange', 'AdminController@updatePassword')->name('admin-panal.password');

    Route::resource('/admin-panal/users', 'UsersController');
    Route::resource('/admin-panal/admins', 'AdminController');
    Route::resource('/admin-panal/tags', 'TagsController');
    Route::resource('/admin-panal/colors', 'ColorsController');
    Route::resource('/admin-panal/sizes', 'SizesController');
    Route::resource('/admin-panal/contacts', 'ContactsContoller');
    Route::resource('/admin-panal/sliders', 'SliderController');
    Route::resource('/admin-panal/banners', 'BannersController');
    Route::resource('/admin-panal/faqs', 'FaqController');
    Route::resource('/admin-panal/blogs', 'PostsController');
    Route::resource('/admin-panal/products', 'ProductsController');
    Route::resource('/admin-panal/categories', 'CategoriesController');
    Route::resource('/admin-panal/orders', 'OrdersController');
    

    //==================================================================================
    
    Route::get('/admin-panal/products/{id}/restore', 'ProductsController@restore')->name('products.restore');
    Route::get('/admin-panal/products/get/trashed', 'ProductsController@getTrashed')->name('products.trash');
    Route::get('/admin-panal/products/{id}/ForceDelete', 'ProductsController@ForceDelete')->name('products.forcedelete');

    //==================================================================================

    Route::get('/admin-panal/banners/{id}/restore', 'BannersController@restore')->name('banners.restore');
    Route::get('/admin-panal/banners/get/trashed', 'BannersController@getTrashed')->name('banners.trash');
    Route::get('/admin-panal/banners/{id}/ForceDelete', 'BannersController@ForceDelete')->name('banners.forcedelete');

    //==================================================================================

    Route::get('/admin-panal/users/{id}/restore', 'UsersController@restore')->name('users.restore');
    Route::get('/admin-panal/users/get/trashed', 'UsersController@getTrashed')->name('users.trash');
    Route::get('/admin-panal/users/{id}/ForceDelete', 'UsersController@forceDelete')->name('users.forcedelete');

    //==================================================================================
    
    Route::get('/admin-panal/blogs/{id}/restore', 'PostsController@restore')->name('blogs.restore');
    Route::get('/admin-panal/blogs/get/trashed', 'PostsController@getTrashed')->name('blogs.trash');
    Route::get('/admin-panal/blogs/{id}/ForceDelete', 'PostsController@forceDelete')->name('blogs.forcedelete');

    //==================================================================================

    Route::get('/admin-panal/orders/{id}/restore', 'OrdersController@restore')->name('orders.restore');
    Route::get('/admin-panal/orders/get/trashed', 'OrdersController@getTrashed')->name('orders.trash');
    Route::get('/admin-panal/orders/{id}/ForceDelete', 'OrdersController@forceDelete')->name('orders.forcedelete');

    //===================================================================================

    Route::get('/admin-panal/sliders/{id}/restore', 'SliderController@restore')->name('sliders.restore');
    Route::get('/admin-panal/sliders/get/trashed', 'SliderController@getTrashed')->name('sliders.trash');
    Route::get('/admin-panal/sliders/{id}/ForceDelete', 'SliderController@ForceDelete')->name('sliders.forcedelete');

    Route::get('/MarkAllSeen', 'ContactsContoller@AllSeen');
    Route::get('/getcontactid/{image}/{subject}', 'ContactsContoller@GetContactId');

});

// ===================================================================================================================
// ===================================================================================================================

Route::group(['middleware' => ['web', 'lang']], function () {

    Route::get('/change/lang/{lang}', 'HomeController@langs')->middleware('auth');

    Route::get('/products/category/i/{category_id}/{category_name}', 'HomeController@getCategory')->name('products.category')->middleware('web');
    
    Route::get('/products/i/{id}/{name}', 'ProductsController@Product')->name('home.product')->middleware('web');

    // Ajax Requests
    Route::get('/ajax/products/information/', 'ProductsController@getAjaxProducts')->middleware('web');
    Route::get('/ajax/cart/create/', 'CartController@setAjaxCart');
    Route::get('/ajax/cart/removeProductFromCart/', 'CartController@removeProductFromCart');
    Route::get('/ajax/Wishlist/removeProductFromWishlist/', 'CartController@removeProductFromWishlist');

    Route::get('/ajax/cart/count/', 'CartController@setCartCount');
    Route::get('/ajax/cart/total/', 'CartController@getCartTotal');
    Route::get('/ajax/wishlist/content/', 'CartController@addToWishlist');
    Route::get('/ajax/wishlist/count/', 'CartController@getWishlistCount');
    Route::get('/ajax/cart/update/qty/', 'CartController@changeQty');
    Route::get('/ajax/moveToCart/', 'CartController@moveToCart');
    Route::get('/ajax/cart/showcartmodel/', 'CartController@getShowCartModel');
    
    // End Ajax Requests
    

    Route::post('/products/i/{id}/{name}', 'ProductsController@Review')->name('products')->middleware('auth');
    Route::post('/home/shopping-cart/checkout', 'OrdersController@store')->name('orders')->middleware('auth');

    
    Route::get('/products/filter/', 'ProductsController@GetFilter');
    Route::post('/products/filter/', 'ProductsController@FilterSorting')->middleware(['web', 'lang']);
    
    Route::view('/contact-us', 'site.pages.contact-us')->name('contact-us')->middleware('web');
    Route::post('/contact-us', 'ContactsContoller@store')->middleware('auth');
    
    Route::view('/about-us', 'site.pages.about-us')->name('about-us')->middleware('web');
    Route::view('/F&Qs', 'site.pages.faq')->name('faqs');
    Route::get('/shop', 'HomeController@Shop')->name('shop')->middleware('web');
    
    Route::get('/blog', 'PostsController@blog')->name('blog')->middleware('web');
    Route::get('/blog/i/{id}/{name}', 'PostsController@blogdetiles')->name('blog-details')->middleware('web');
    Route::post('/blog/i/{id}/{name}', 'PostsController@AddNewComment')->middleware('auth');

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home/shopping-cart', 'CartController@index')->name('cart.index')->middleware('auth');
    Route::post('/home/shopping-cart', 'CartController@store')->name('cart.store')->middleware('auth');
    Route::get('/home/profile/{username}', 'HomeController@profile')->name('home.profile')->middleware('auth');

    // Tags
    Route::get('/tags/colors/i/{id}/{color}', 'HomeController@ColorsTags');
    Route::get('/tags/products/i/{id}/{tag}', 'HomeController@ProductTags');
    Route::get('/tags/sizes/i/{id}/{size}', 'HomeController@SizesTags');
    Route::get('/tags/blog/i/{id}/{name}', 'HomeController@BlogsTags');

    Route::post('/cart/addToWishlist/', 'CartController@addToWishlist')->middleware('auth');
    
    Route::post('/home/users/PasswordChange', 'UsersController@UserChangePasssword');
    Route::get('/home/shopping-cart/checkout', 'CheckoutController@index')->name('checkout.index');
});

resources/views/admin/index.blade.php
@extends('admin.layout.master')

@section('title', 'الرئيسية')

@section('content')

<section class="content-header">
	<h1 class="pull-right hidden-xs hidden-sm" dir="rtl"> الرئيسية <small>رئيسية {{ text(GetSettings('sitename')) }}</small></h1>
	<ol class="breadcrumb">
		<li class="active h4"><i class="fa fa-dashboard"></i> الرئيسية</li>
	</ol>
</section>

<br><br>

<section class="content" style="padding: 20px; margin: 20px;">
	<br>
	<div class="row">
		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<span class="info-box-icon bg-aqua"><i class="ion ion-ios-contact-outline"></i></span>

				<div class="info-box-content">
					<span class="info-box-text">الاعضاء</span>
					<span class="info-box-number">{{ users() }}</span>
				</div>
			</div>
		</div>

		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<span class="info-box-icon bg-blue"><i class="ion ion-ios-cart"></i></span>

				<div class="info-box-content">
					<span class="info-box-text">المنتجات</span>
					<span class="info-box-number">{{ AllProductsCount() }}</span>
				</div>

			</div>
		</div>

		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<span class="info-box-icon bg-green"><i class="ion ion-ios-cart"></i></span>

				<div class="info-box-content">
					<span class="info-box-text">المنتجات المفعلة</span>
					<span class="info-box-number">{{ ProductsStatusCount(1) }}</span>
				</div>

			</div>
		</div>

		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<span class="info-box-icon bg-red"><i class="ion ion-ios-cart"></i></span>

				<div class="info-box-content">
					<span class="info-box-text">المنتجات الغير مغعلة</span>
					<span class="info-box-number">{{ ProductsStatusCount(0) }}</span>
				</div>

			</div>
		</div>

		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<span class="info-box-icon bg-silver"><i class="ion ion-ios-cart"></i></span>

				<div class="info-box-content">
					<span class="info-box-text">المنتجات المحذوفة</span>
					<span class="info-box-number">{{ GetDeletedProductsCount() }}</span>
				</div>

			</div>
		</div>

		<div class="clearfix visible-sm-block"></div>

		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<span class="info-box-icon bg-purple"><i class="ion ion-chatbubbles"></i></span>

				<div class="info-box-content">
					<span class="info-box-text">رسائل الاعضاء</span>
					<span class="info-box-number">{{ getAllMessagesCount() }}</span>
				</div>

			</div>
		</div>

		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<span class="info-box-icon bg-navy"><i class="ion ion-chatbubbles"></i></span>

				<div class="info-box-content">
					<span class="info-box-text">الرسائل الغير مقروءة</span>
					<span class="info-box-number">{{ count($auth->unreadNotifications) }}</span>
				</div>

			</div>
		</div>

		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<span class="info-box-icon bg-yellow"><i class="ion ion-ios-at-outline"></i></span>

				<div class="info-box-content">
					<span class="info-box-text">الرسائل المقروءة</span>
					<span class="info-box-number">{{ getreadedMessagesCount() }}</span>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		{{-- Products Charts --}}
		<div class="col-md-8">
			<div class="box">
				
				<div class="box-header with-border">
					<h3 class="box-title">{{ __('تقرير المبيعات السنوي') }}</h3>

					<div class="box-tools pull-right">
						
						<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
						
						<div class="btn-group">
							
							<button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-wrench"></i>
							</button>

						</div>
						<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
					</div>
				</div>

				<div class="box-body">
					<div class="row">
						<div class="col-md-12">
							<p class="text-center">
								<strong>مخطط للمنتجات علي مدار العام</strong>
							</p>

							<div class="chart">
								<canvas id="salesChart" style="height: 180px;"></canvas>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
		
		{{-- Special Members --}}
		<div class="col-md-4">
			<div class="box box-danger">
				
				<div class="box-header with-border">
					<h3 class="box-title">{{ ('مديرين مميزين') }}</h3>
					<div class="box-tools pull-right">
						<span class="label label-danger">{{ ('مديرين مميزين') }}</span>
						<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
						<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
					</div>
				</div>
				
				<div class="box-body no-padding">
					<ul class="users-list clearfix">
						@forelse(GetSpecialAdmins() as $usercount)
						@php
							$user_image = GetImage($usercount->image, '/public/advent/uploads/users/', '/advent/uploads/users/');
							$fullname = getFullname($usercount->id);
						@endphp
						<li>
							<img title="{{ $fullname }}" src="{{ $user_image }}" alt="{{ $fullname }}">
							<a class="users-list-name" href="{{ route('admins.show', $usercount->id) }}" title="{{ $fullname }}">
								{{ $fullname }}
							</a>
							<span class="users-list-date">{{ $usercount->count }}</span>
						</li>
						@empty
						<li>
							<div class="alert alert-info" role="alert">عفوا لا يوجد مشرفين حاليا</div>
						</li>
						@endforelse
					</ul>
				</div>

				<div class="box-footer text-center">
					<a href="{{ route('users.index') }}" class="uppercase">عرض جميع الاعضاء</a>
				</div>
			</div>
		</div>
	</div>

	{{-- latest Members --}}
	<div class="row">
		<div class="col-md-12">
			<div class="box box-danger">
				
				<div class="box-header with-border">
					<h3 class="box-title">أحدث الاعضاء</h3>
	
					<div class="box-tools pull-right">
						<span class="label label-danger">أحدث 8 أعضاء</span>
						<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
						<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
					</div>
				</div>
				
				<div class="box-body no-padding">
					<ul class="users-list clearfix">
						@forelse(leatestUsers() as $last)
						@php 
							$image = GetImage($last->image, '/public/advent/uploads/users/', '/advent/uploads/users/');
							$fullname = ucfirst($last->firstName).' '.ucfirst($last->lastName);
						@endphp
						<li>
							<img width="300" src="{{ $image }}" alt="User Image">
							<a class="users-list-name" href="{{ route('users.edit', $last->id) }}" title="{{ $fullname  }}">
								<h3>{{ $fullname  }}</h3>
							</a>
							<span class="users-list-date">
								<h4>{{ \Carbon\Carbon::parse($last->created_at)->diffForHumans() }}</h4>
							</span>
						</li>
						@empty
						<li>
							<div class="alert alert-info" role="alert">عفوا لا يوجد اعضاء حايلا</div>
						</li>
						@endforelse
					</ul>
				</div>
	
				<div class="box-footer text-center">
					<a href="{{ route('users.index') }}" class="uppercase">عرض جميع الاعضاء</a>
				</div>
			</div>
		</div>
	</div>
	
	{{-- latest Orders --}}
	<div class="row">
		<div class="col-md-12">
			<div class="box box-info">
				
				<div class="box-header with-border">
					<h3 class="box-title">{{ __('أخر الطلبات') }}</h3>
	
					<div class="box-tools pull-right">
						<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
						<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
					</div>
				</div>
	
				<div class="box-body">
					<div class="table-responsive">
						<table class="table no-margin">
							<thead class="h4">
	                            <tr>
	                                <th>{{ __('#') }}</th>
	                                <th>إسم العميل</th>
	                                <th>عدد المنتجات</th>
	                                <th>الاجمالي</th>
	                            </tr>
	                        </thead>
	                        <tbody class="h4">
	                        	@forelse(App\Order::latest()->take(5)->get() as $trashed)
	                        	@php $ord = json_decode($trashed->products); @endphp
	                        	<tr>
	                        		<td>{{ $trashed->id }}</td>
	                        		<td>
	                        			<a href="{{ route('orders.show', $trashed->id) }}">
	                        				{{ 
		                        				ucfirst(getOrderedUser($trashed->custumer_id)->firstName).
		                        				' '.
		                        				ucfirst(getOrderedUser($trashed->custumer_id)->lastName) 
		                        			}}
	                        			</a>
	                        		</td>
	                        		<td>{{ count($ord->ids) }}</td>
	                        		<td>{{ getCurrence($trashed->total) }}</td>
	                        	</tr>
	                        	@empty
	                        	<tr>
	                        		<td colspan="4" class="text-center h2"><b>{{ __('لا يوجد طلبات') }}</b></td>
	                        	</tr>
	                        	@endforelse
	                        </tbody>
						</table>
					</div>
				</div>
	
				<div class="box-footer clearfix">
					<a href="{{ route('orders.index') }}" class="btn btn-sm btn-default btn-flat pull-right">View All Orders</a>
				</div>
			</div>
		</div>
	</div>

</section>
@stop
@section('script')
	@include('admin.inc.chart')
@stop