routes/web.php
<?php

Route::get('/', 'HomeController@welcome')->middleware('lang');
Auth::routes();

Route::get('/admin-panal/login', 'Auth\AdminLoginController@showLoginForm')->name('admin-panal.login');
Route::post('/admin-panal/login', 'Auth\AdminLoginController@login')->name('admin-panal.login.submit');

Route::group(['middleware' => 'auth:admin'], function ()
{   
    Route::get('/admin-panal/contacts/data', 'ContactsContoller@anyData');
    Route::get('/admin-panal/users/data', 'UsersController@anyData');
    Route::get('/admin-panal/products/data', 'ProductsController@anyData');
    Route::get('/admin-panal/orders/data', 'OrdersController@anyData');
    
    Route::get('/admin-panal', 'AdminController@index')->name('admin-panal');

    Route::get('/admin-panal/contacts/{id}/destroy', 'ContactsContoller@destroy');
    Route::get('/admin-panal/orders/{id}/destroy', 'OrdersController@destroy');
    Route::get('/admin-panal/faqs/{id}/destroy', 'FaqsController@destroy');
    Route::get('/admin-panal/users/{id}/destroy', 'UsersController@destroy');
    Route::get('/admin-panal/colors/{id}/destroy', 'ColorsController@destroy');
    Route::get('/admin-panal/products/{id}/destroy', 'ProductsController@destroy');
    Route::get('/admin-panal/blogs/{id}/destroy', 'PostsController@destroy');
    Route::get('/admin-panal/sizes/{id}/destroy', 'SizesController@destroy');
    
    Route::get('/admin-panal/contacts/remove-all', 'ContactsContoller@RemoveAll')->name('contacts.remove-all');
    Route::get('/admin-panal/products/id/{id}/{name}/', 'ProductsController@ShowMeProduct');
    Route::get('/admin-panal/contacts/{id}/edit', 'ContactsContoller@edit');
    Route::get('/admin-panal/settings', 'SettingsController@index')->name('settings');
    Route::view('/admin-panal/settings/create', 'admin.settings.add')->name('settings.create');
    Route::post('/admin-panal/settings/create', 'SettingsController@addnewset')->name('settings.addnewset');
    Route::post('/admin-panal/settings', 'SettingsController@store');

    Route::get('/admin-panal/blogs/i/{id}/{name}', 'PostsController@ShowBlog');
    Route::get('/admin-panal/blogs/i/{id}/{name}/edit', 'PostsController@BlogEdit');
    
    Route::post('/admin-panal/users/PasswordChange', 'UsersController@updatePassword');
    Route::post('/admin-panal/users/PasswordChange', 'AdminController@updatePassword')->name('admin-panal.password');

    Route::resource('/admin-panal/users', 'UsersController');
    Route::resource('/admin-panal/admins', 'AdminController');
    Route::resource('/admin-panal/tags', 'TagsController');
    Route::resource('/admin-panal/colors', 'ColorsController');
    Route::resource('/admin-panal/sizes', 'SizesController');
    Route::resource('/admin-panal/contacts', 'ContactsContoller');
    Route::resource('/admin-panal/sliders', 'SliderController');
    Route::resource('/admin-panal/banners', 'BannersController');
    Route::resource('/admin-panal/faqs', 'FaqController');
    Route::resource('/admin-panal/blogs', 'PostsController');
    Route::resource('/admin-panal/products', 'ProductsController');
    Route::resource('/admin-panal/categories', 'CategoriesController');
    Route::resource('/admin-panal/orders', 'OrdersController');
    

    //==================================================================================
    
    Route::get('/admin-panal/products/{id}/restore', 'ProductsController@restore')->name('products.restore');
    Route::get('/admin-panal/products/get/trashed', 'ProductsController@getTrashed')->name('products.trash');
    Route::get('/admin-panal/products/{id}/ForceDelete', 'ProductsController@ForceDelete')->name('products.forcedelete');

    //==================================================================================

    Route::get('/admin-panal/banners/{id}/restore', 'BannersController@restore')->name('banners.restore');
    Route::get('/admin-panal/banners/get/trashed', 'BannersController@getTrashed')->name('banners.trash');
    Route::get('/admin-panal/banners/{id}/ForceDelete', 'BannersController@ForceDelete')->name('banners.forcedelete');

    //==================================================================================

    Route::get('/admin-panal/users/{id}/restore', 'UsersController@restore')->name('users.restore');
    Route::get('/admin-panal/users/get/trashed', 'UsersController@getTrashed')->name('users.trash');
    Route::get('/admin-panal/users/{id}/ForceDelete', 'UsersController@forceDelete')->name('users.forcedelete');

    //==================================================================================
    
    Route::get('/admin-panal/blogs/{id}/restore', 'PostsController@restore')->name('blogs.restore');
    Route::get('/admin-panal/blogs/get/trashed', 'PostsController@getTrashed')->name('blogs.trash');
    Route::get('/admin-panal/blogs/{id}/ForceDelete', 'PostsController@forceDelete')->name('blogs.forcedelete');

    //==================================================================================

    Route::get('/admin-panal/orders/{id}/restore', 'OrdersController@restore')->name('orders.restore');
    Route::get('/admin-panal/orders/get/trashed', 'OrdersController@getTrashed')->name('orders.trash');
    Route::get('/admin-panal/orders/{id}/ForceDelete', 'OrdersController@forceDelete')->name('orders.forcedelete');

    //===================================================================================

    Route::get('/admin-panal/sliders/{id}/restore', 'SliderController@restore')->name('sliders.restore');
    Route::get('/admin-panal/sliders/get/trashed', 'SliderController@getTrashed')->name('sliders.trash');
    Route::get('/admin-panal/sliders/{id}/ForceDelete', 'SliderController@ForceDelete')->name('sliders.forcedelete');

    Route::get('/MarkAllSeen', 'ContactsContoller@AllSeen');
    Route::get('/getcontactid/{image}/{subject}', 'ContactsContoller@GetContactId');

});

// ===================================================================================================================
// ===================================================================================================================

Route::group(['middleware' => ['web', 'lang']], function () {

    Route::get('/change/lang/{lang}', 'HomeController@langs')->middleware('auth');

    Route::get('/products/category/i/{category_id}/{category_name}', 'HomeController@getCategory')->name('products.category')->middleware('web');
    
    Route::get('/products/i/{id}/{name}', 'ProductsController@Product')->name('home.product')->middleware('web');

    // Ajax Requests
    Route::get('/ajax/products/information/', 'ProductsController@getAjaxProducts')->middleware('web');
    Route::get('/ajax/cart/create/', 'CartController@setAjaxCart');
    Route::get('/ajax/cart/removeProductFromCart/', 'CartController@removeProductFromCart');
    Route::get('/ajax/Wishlist/removeProductFromWishlist/', 'CartController@removeProductFromWishlist');

    Route::get('/ajax/cart/count/', 'CartController@setCartCount');
    Route::get('/ajax/cart/total/', 'CartController@getCartTotal');
    Route::get('/ajax/wishlist/content/', 'CartController@addToWishlist');
    Route::get('/ajax/wishlist/count/', 'CartController@getWishlistCount');
    Route::get('/ajax/cart/update/qty/', 'CartController@changeQty');
    Route::get('/ajax/moveToCart/', 'CartController@moveToCart');
    Route::get('/ajax/cart/showcartmodel/', 'CartController@getShowCartModel');
    
    // End Ajax Requests
    

    Route::post('/products/i/{id}/{name}', 'ProductsController@Review')->name('products')->middleware('auth');
    Route::post('/home/shopping-cart/checkout', 'OrdersController@store')->name('orders')->middleware('auth');

    
    Route::get('/products/filter/', 'ProductsController@GetFilter');
    Route::post('/products/filter/', 'ProductsController@FilterSorting')->middleware(['web', 'lang']);
    
    Route::view('/contact-us', 'site.pages.contact-us')->name('contact-us')->middleware('web');
    Route::post('/contact-us', 'ContactsContoller@store')->middleware('auth');
    
    Route::view('/about-us', 'site.pages.about-us')->name('about-us')->middleware('web');
    Route::view('/F&Qs', 'site.pages.faq')->name('faqs');
    Route::get('/shop', 'HomeController@Shop')->name('shop')->middleware('web');
    
    Route::get('/blog', 'PostsController@blog')->name('blog')->middleware('web');
    Route::get('/blog/i/{id}/{name}', 'PostsController@blogdetiles')->name('blog-details')->middleware('web');
    Route::post('/blog/i/{id}/{name}', 'PostsController@AddNewComment')->middleware('auth');

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home/shopping-cart', 'CartController@index')->name('cart.index')->middleware('auth');
    Route::post('/home/shopping-cart', 'CartController@store')->name('cart.store')->middleware('auth');
    Route::get('/home/profile/{username}', 'HomeController@profile')->name('home.profile')->middleware('auth');

    // Tags
    Route::get('/tags/colors/i/{id}/{color}', 'HomeController@ColorsTags');
    Route::get('/tags/products/i/{id}/{tag}', 'HomeController@ProductTags');
    Route::get('/tags/sizes/i/{id}/{size}', 'HomeController@SizesTags');
    Route::get('/tags/blog/i/{id}/{name}', 'HomeController@BlogsTags');

    Route::post('/cart/addToWishlist/', 'CartController@addToWishlist')->middleware('auth');
    
    Route::post('/home/users/PasswordChange', 'UsersController@UserChangePasssword');
    Route::get('/home/shopping-cart/checkout', 'CheckoutController@index')->name('checkout.index');
});

resources/views/admin/inc/chart.blade.php
<script type="text/javascript">

    // -----------------------
    // - MONTHLY SALES CHART -
    // -----------------------

    // Get context with jQuery - using jQuery's .get() method.
    var salesChartCanvas = $('#salesChart').get(0).getContext('2d');
    
    // This will get the first returned node in the jQuery collection.
    var salesChart  = new Chart(salesChartCanvas);

    var salesChartData = {
        labels  : ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        datasets: [{
            label               : 'Digital Goods',
            fillColor           : 'rgba(60,141,188,0.9)',
            strokeColor         : 'rgba(60,141,188,0.8)',
            pointColor          : '#3b8bba',
            pointStrokeColor    : 'rgba(60,141,188,1)',
            pointHighlightFill  : '#fff',
            pointHighlightStroke: 'rgba(60,141,188,1)',
            data : [@foreach($new as $chart){{ (is_array($chart)) ? $chart['count'].',' : $chart.',' }}@endforeach]
        }]
    };

    var salesChartOptions = {

    // Boolean - If we should show the scale at all
    showScale               : true,
    
    // Boolean - Whether grid lines are shown across the chart
    scaleShowGridLines      : false,
    
    // String - Colour of the grid lines
    scaleGridLineColor      : 'rgba(0,0,0,.05)',
    
    // Number - Width of the grid lines
    scaleGridLineWidth      : 1,
    
    // Boolean - Whether to show horizontal lines (except X axis)
    scaleShowHorizontalLines: true,
    
    // Boolean - Whether to show vertical lines (except Y axis)
    scaleShowVerticalLines  : true,
    
    // Boolean - Whether the line is curved between points
    bezierCurve             : true,
    
    // Number - Tension of the bezier curve between points
    bezierCurveTension      : 0.3,
    
    // Boolean - Whether to show a dot for each point
    pointDot                : false,
    
    // Number - Radius of each point dot in pixels
    pointDotRadius          : 4,
    
    // Number - Pixel width of point dot stroke
    pointDotStrokeWidth     : 1,
    
    // Number - amount extra to add to the radius to cater for hit detection outside the drawn point
    pointHitDetectionRadius : 20,
    
    // Boolean - Whether to show a stroke for datasets
    datasetStroke           : true,
    
    // Number - Pixel width of dataset stroke
    datasetStrokeWidth      : 2,
    
    // Boolean - Whether to fill the dataset with a color
    datasetFill             : true,
    
    // String - A legend template
    legendTemplate          : '<ul class=\'<%=name.toLowerCase()%>-legend\'><% for (var i=0; i<datasets.length; i++){%><li><span style=\'background-color:<%=datasets[i].lineColor%>\'></span><%=datasets[i].label%></li><%}%></ul>',
    
    // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
    maintainAspectRatio     : true,
    
    // Boolean - whether to make the chart responsive to window resizing
    responsive              : true
  };
</script>

resources/views/admin/inc/footer.blade.php
<footer class="main-footer" style="direction: rtl;">
	<div class="pull-left hidden-xs">
		2.4.0 <b>النسخة</b>
	</div>
	<strong>حقوق الملكية &copy; 2014-{{ date('Y') }} <a href="https://adminlte.io">المسيد استوديو</a>.</strong> جميع الحقوق محفوظة
</footer>
<div class="control-sidebar-bg"></div>

resources/views/admin/inc/header.blade.php
@php 
	$admin_image = GetImage($auth->image, '/public/advent/uploads/users/', '/advent/uploads/users/'); 
@endphp

<style>
	.unread{ padding:10px;background-color:#e5e5e5;}
</style>

<header class="main-header">
	<a href="{{ route('admin-panal') }}" class="logo">
		<span class="logo-mini"><b>تحكم</b></span>
		<span class="logo-lg"><b>لوحة </b> تحكم الموقع</span>
	</a>
	
	<nav class="navbar navbar-static-top">
		<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"><span class="sr-only">Toggle navigation</span></a>
		
		<div class="navbar-custom-menu">
			<ul class="nav navbar-nav">
				
				<li class="dropdown messages-menu">
					
					<a href="#" class="dropdown-toggle notificaiton" data-toggle="dropdown">
						<i class="fa fa-envelope-o"></i>
						<span class="label label-success" id="count">{{ count($auth->unreadNotifications) }}</span>
					</a>
					
					<ul class="dropdown-menu">
						<li class="header">
							لديك {{ count($auth->unreadNotifications) }} رسائل غير مقروء 
						</li>
						<li>
							<ul class="menu" id="showNofication">
								@forelse($auth->notifications as $notification)
								@php
									$img = GetImage($notification->data['image'], '/public/advent/uploads/users/', '/advent/uploads/users/');
									$if = (($notification->read_at == null) ? 'unread' : 'p-10-all');
									$co_id = $notification->data['id'];
									$not_id = $notification->id;
								@endphp
								<li>
									<a class="{{ $if }}" href="{{ url($root.'/admin-panal/contacts/'.$co_id.'/edit/?id='.$not_id) }}">
										
										<div class="pull-left"><img src="{{ $img }}" class="img-circle" alt="User Image"></div>
										
										<h4>
											{{ $notification->data['name'] }}
											<small>
												<i class="fa fa-clock-o"></i>&nbsp;
												{{ $notification->data['created_at'] }}
											</small>
										</h4>
										
										<p>
											<span>
												<i class="label label-info"></i>
												{{ 'Subject : '.$notification->data['subject'] }}
											</span>
											<br>
											{{ str_limit($notification->data['subject'], 20) }}
										</p>
										
									</a>
								</li>
								@empty
									<li class="text-center" style="padding:10px;background-color:#3c8dbc;color:white;">{{ __('لا يوجد رسائل') }}</li>
								@endforelse
							</ul>
						</li>
						<li class="footer"><a href="{{ route('contacts.index') }}">مشاهدة جميع الرسائل</a></li>
					</ul>
				</li>
				
				<li class="dropdown user user-menu">
					
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<img src="{{ $admin_image }}"  class="user-image" alt="User Image">
						<span class="hidden-xs">{{ $auth->username }}</span>
						<div class="clearfix"></div>
					</a>
					
					<ul class="dropdown-menu">
						
						<li class="user-header">
							<img src="{{ $admin_image }}" class="img-circle" alt="User Image">
							<p>
								{{ getFullname($auth->id) }} - {{ $auth->jop }}<small>عضو منذ عام. {{ $auth->created_at->year }}</small>
							</p>
						</li>
						
						<li class="user-footer">
							
							<div class="pull-left">
								<a href="{{ route('admins.show', $auth->id) }}" class="btn btn-default btn-flat">الملف الشخصي</a>
							</div>
							
							<div class="pull-right">
								<a class="btn btn-default btn-flat" href="{{ route('logout') }}"
								onclick="event.preventDefault();document.getElementById('logout-form').submit();">
								{{ __('تسجيل الخروج') }}
								</a>
								<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
									@csrf
								</form>
							</div>
						</li>

					</ul>
				</li>
			
			</ul>
		</div>
	</nav>
</header>

resources/views/admin/inc/map.blade.php
<script type="text/javascript">

	/* 
	** jVector Maps
   	** Create a world map with markers
   	**/

   	$('#world-map-markers').vectorMap({
   		map              : 'world_mill_en',
	    normalizeFunction: 'polynomial',
	    hoverOpacity     : 0.7,
	    hoverColor       : true,
	    backgroundColor  : 'transparent',
	    regionStyle      : {
	    	initial      : {
	    		fill            : 'rgba(210, 214, 222, 1)', 'fill-opacity'  : 1,
	    		stroke          : 'none', 'stroke-width'  : 0, 'stroke-opacity': 1
	    	},
	    	hover        : {
	    		'fill-opacity': 0.7,
	    		cursor        : 'pointer'
	    	},
	    	selected     : {
	    		fill: 'yellow'
	    	},
	    	selectedHover: {}
	    },
	    markerStyle      : {
	    	initial: {
	    		fill  : '#00a65a',
	    		stroke: '#111'
	    	}
	    },
	    markers          : [
	    	@foreach($maps as $map)
	    		{ latLng: [{{ $map->bu_latitude }}, {{ $map->bu_langtude }}], name: '{{ $map->bu_name }}' },
    		@endforeach
    	]
  	});
</script>

resources/views/admin/inc/sidebar.blade.php
@php
	$admin_image = GetImage($auth->image, '/public/advent/uploads/users/', '/advent/uploads/users/');
@endphp
<aside class="main-sidebar">

	<section class="sidebar">
		<div class="user-panel">
			<div class="pull-left image">
				<img src="{{ $admin_image }}" class="img-circle" alt="User Image">
			</div>
			<div class="pull-left info">
				<p>{{ $auth->name }}</p>
				<a href="#"><i class="fa fa-circle text-success"></i> متصل</a>
			</div>
		</div>

		<form action="javascript:void(0);" method="get" class="sidebar-form">
			<div class="input-group">
				<input type="text" name="q" class="form-control" placeholder="ابحث...">
				<span class="input-group-btn">
					<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
				</span>
			</div>
		</form>

		<ul class="sidebar-menu" data-widget="tree">
			<li class="header">MAIN NAVIGATION</li>
			
			<li><a href="{{ route('admin-panal') }}"><i class="fa fa-dashboard"></i> <span>الرئسية</span></a></li>
			
			<li class="treeview">
				<a href="#">
					<i class="fa fa-users"></i> <span>الاعضاء</span>
					<span class="pull-right-container">
						<i class="fa fa-angle-left pull-right"></i>
					</span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('users.create') }}"><i class="fa fa-circle-o"></i>اضافة عضو جديد</a></li>
					<li><a href="{{ route('users.index') }}"><i class="fa fa-circle-o"></i> عرض جميع الاعضاء</a></li>
					<li><a href="{{ route('users.trash') }}"><i class="fa fa-circle-o"></i> عرض جميع الاعضاء المحذوفة</a></li>
				</ul>
			</li>

			<li><a href="{{ route('contacts.index') }}"><i class="fa fa-address-book"></i> <span>عرض جميع الرسائل</span></a></li>			
				
			<li class="treeview">
				<a href="#">
					<i class="fa fa-id-card-o" aria-hidden="true"></i> <span>الطلبات</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('orders.index') }}"><i class="fa fa-circle-o"></i> <span>عرض جميع الطلبات</span></a></li>
					<li><a href="{{ route('orders.trash') }}"><i class="fa fa-circle-o"></i> <span>عرض الطلبات المكتملة</span></a></li>
				</ul>
			</li>		
			
			<li class="treeview">
				<a href="#">
					<i class="fa fa-comments" aria-hidden="true"></i> <span>المدونة</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('blogs.create') }}"><i class="fa fa-circle-o"></i>كتابة تدوينة جديدة</a></li>
					<li><a href="{{ route('blogs.index') }}"><i class="fa fa-circle-o"></i> عرض جميع التدوينات</a></li>
					<li><a href="{{ route('blogs.trash') }}"><i class="fa fa-circle-o"></i> عرض جميع التدوينات المحذوفة</a></li>
				</ul>
			</li>

			<li class="treeview">
				<a href="#">
					<i class="fa fa-tag" aria-hidden="true"></i> <span>الكلمات الدلالية</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('tags.create') }}"><i class="fa fa-circle-o"></i>إضافة كلمة دلالية جديدة</a></li>
					<li><a href="{{ route('tags.index') }}"><i class="fa fa-circle-o"></i> عرض جميع الكلمات الدلالية</a></li>
				</ul>
			</li>

			<li class="treeview">
				<a href="#">
					<i class="fa fa-paint-brush" aria-hidden="true"></i> <span>الالوان</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('colors.create') }}"><i class="fa fa-circle-o"></i>إضافة  لون جديد</a></li>
					<li><a href="{{ route('colors.index') }}"><i class="fa fa-circle-o"></i> عرض جميع  الالوان</a></li>
				</ul>
			</li>

			<li class="treeview">
				<a href="#">
					<i class="fa fa-windows" aria-hidden="true"></i> <span>الاسئلة الشائعة</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('faqs.create') }}"><i class="fa fa-circle-o"></i>إضافة سؤال جديد</a></li>
					<li><a href="{{ route('faqs.index') }}"><i class="fa fa-circle-o"></i>عرض جميع الأسئلة</a></li>
				</ul>
			</li>

			<li class="treeview">
				<a href="#">
					<i class="fa fa-grav" aria-hidden="true"></i> <span>المقاسات</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('sizes.create') }}"><i class="fa fa-circle-o"></i>إضافة مقاس جديد</a></li>
					<li><a href="{{ route('sizes.index') }}"><i class="fa fa-circle-o"></i> عرض جميع  المقاسات</a></li>
				</ul>
			</li>

			<li class="treeview">
				<a href="#">
					<i class="fa fa-amazon" aria-hidden="true"></i> <span>المنتجات</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('products.create') }}"><i class="fa fa-circle-o"></i>اضافة منتج جديد</a></li>
					<li><a href="{{ route('products.index') }}"><i class="fa fa-circle-o"></i> عرض جميع المنتجات</a></li>
					<li><a href="{{ route('products.trash') }}"><i class="fa fa-circle-o"></i> عرض جميع المنتجات المحذوفة</a></li>
				</ul>
			</li>
			
			<li class="treeview">
				<a href="#">
					<i class="fa fa-gear" aria-hidden="true"></i> <span>الاعدادات</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('settings.create') }}"><i class="fa fa-circle-o"></i>اضافةإعداد جديد</a></li>
					<li><a href="{{ route('settings') }}"><i class="fa fa-circle-o"></i> عرض جميع الإعدادات</a></li>
				</ul>
			</li>

			<li class="treeview">
				<a href="#">
					<i class="fa fa-meetup" aria-hidden="true"></i> <span>البنر</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('sliders.create') }}"><i class="fa fa-circle-o"></i>إضافة بندر جديد</a></li>
					<li><a href="{{ route('sliders.index') }}"><i class="fa fa-circle-o"></i> عرض جميع البنرات</a></li>
					<li><a href="{{ route('sliders.trash') }}"><i class="fa fa-circle-o"></i> عرض جميع البنرات المحذوفة</a></li>
				</ul>
			</li>

			<li class="treeview">
				<a href="#">
					<i class="fa fa-podcast" aria-hidden="true"></i> <span>الاقسام</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('banners.create') }}"><i class="fa fa-circle-o"></i>إضافة قسم جديد</a></li>
					<li><a href="{{ route('banners.index') }}"><i class="fa fa-circle-o"></i> عرض جميع الاقسام</a></li>
					<li><a href="{{ route('banners.trash') }}"><i class="fa fa-circle-o"></i> عرض جميع الاقسام المحذوفة</a></li>
				</ul>
			</li>

			<li class="treeview">
				<a href="#">
					<i class="fa fa-sliders" aria-hidden="true"></i><span>الفئات</span>
					<span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
				</a>
				<ul class="treeview-menu">
					<li><a href="{{ route('categories.create') }}"><i class="fa fa-circle-o"></i>إضافة فئة جديد</a></li>
					<li><a href="{{ route('categories.index') }}"><i class="fa fa-circle-o"></i> عرض جميع الفئات</a></li>
				</ul>
			</li>

			<li></li>
			<li><a href="{{ url($root) }}" target="_blanck"><i class="fa fa-bug"></i> <span>الموقع</span></a></li>
		</ul>
	</section>
	<br><br><br><br><br><br>
</aside>