routes/web.php
<?php

Route::get('/', 'HomeController@welcome')->middleware('lang');
Auth::routes();

Route::get('/admin-panal/login', 'Auth\AdminLoginController@showLoginForm')->name('admin-panal.login');
Route::post('/admin-panal/login', 'Auth\AdminLoginController@login')->name('admin-panal.login.submit');

Route::group(['middleware' => 'auth:admin'], function ()
{   
    Route::get('/admin-panal/contacts/data', 'ContactsContoller@anyData');
    Route::get('/admin-panal/users/data', 'UsersController@anyData');
    Route::get('/admin-panal/products/data', 'ProductsController@anyData');
    Route::get('/admin-panal/orders/data', 'OrdersController@anyData');
    
    Route::get('/admin-panal', 'AdminController@index')->name('admin-panal');

    Route::get('/admin-panal/contacts/{id}/destroy', 'ContactsContoller@destroy');
    Route::get('/admin-panal/orders/{id}/destroy', 'OrdersController@destroy');
    Route::get('/admin-panal/faqs/{id}/destroy', 'FaqsController@destroy');
    Route::get('/admin-panal/users/{id}/destroy', 'UsersController@destroy');
    Route::get('/admin-panal/colors/{id}/destroy', 'ColorsController@destroy');
    Route::get('/admin-panal/products/{id}/destroy', 'ProductsController@destroy');
    Route::get('/admin-panal/blogs/{id}/destroy', 'PostsController@destroy');
    Route::get('/admin-panal/sizes/{id}/destroy', 'SizesController@destroy');
    
    Route::get('/admin-panal/contacts/remove-all', 'ContactsContoller@RemoveAll')->name('contacts.remove-all');
    Route::get('/admin-panal/products/id/{id}/{name}/', 'ProductsController@ShowMeProduct');
    Route::get('/admin-panal/contacts/{id}/edit', 'ContactsContoller@edit');
    Route::get('/admin-panal/settings', 'SettingsController@index')->name('settings');
    Route::view('/admin-panal/settings/create', 'admin.settings.add')->name('settings.create');
    Route::post('/admin-panal/settings/create', 'SettingsController@addnewset')->name('settings.addnewset');
    Route::post('/admin-panal/settings', 'SettingsController@store');

    Route::get('/admin-panal/blogs/i/{id}/{name}', 'PostsController@ShowBlog');
    Route::get('/admin-panal/blogs/i/{id}/{name}/edit', 'PostsController@BlogEdit');
    
    Route::post('/admin-panal/users/PasswordChange', 'UsersController@updatePassword');
    Route::post('/admin-panal/users/PasswordChange', 'AdminController@updatePassword')->name('admin-panal.password');

    Route::resource('/admin-panal/users', 'UsersController');
    Route::resource('/admin-panal/admins', 'AdminController');
    Route::resource('/admin-panal/tags', 'TagsController');
    Route::resource('/admin-panal/colors', 'ColorsController');
    Route::resource('/admin-panal/sizes', 'SizesController');
    Route::resource('/admin-panal/contacts', 'ContactsContoller');
    Route::resource('/admin-panal/sliders', 'SliderController');
    Route::resource('/admin-panal/banners', 'BannersController');
    Route::resource('/admin-panal/faqs', 'FaqController');
    Route::resource('/admin-panal/blogs', 'PostsController');
    Route::resource('/admin-panal/products', 'ProductsController');
    Route::resource('/admin-panal/categories', 'CategoriesController');
    Route::resource('/admin-panal/orders', 'OrdersController');
    

    //==================================================================================
    
    Route::get('/admin-panal/products/{id}/restore', 'ProductsController@restore')->name('products.restore');
    Route::get('/admin-panal/products/get/trashed', 'ProductsController@getTrashed')->name('products.trash');
    Route::get('/admin-panal/products/{id}/ForceDelete', 'ProductsController@ForceDelete')->name('products.forcedelete');

    //==================================================================================

    Route::get('/admin-panal/banners/{id}/restore', 'BannersController@restore')->name('banners.restore');
    Route::get('/admin-panal/banners/get/trashed', 'BannersController@getTrashed')->name('banners.trash');
    Route::get('/admin-panal/banners/{id}/ForceDelete', 'BannersController@ForceDelete')->name('banners.forcedelete');

    //==================================================================================

    Route::get('/admin-panal/users/{id}/restore', 'UsersController@restore')->name('users.restore');
    Route::get('/admin-panal/users/get/trashed', 'UsersController@getTrashed')->name('users.trash');
    Route::get('/admin-panal/users/{id}/ForceDelete', 'UsersController@forceDelete')->name('users.forcedelete');

    //==================================================================================
    
    Route::get('/admin-panal/blogs/{id}/restore', 'PostsController@restore')->name('blogs.restore');
    Route::get('/admin-panal/blogs/get/trashed', 'PostsController@getTrashed')->name('blogs.trash');
    Route::get('/admin-panal/blogs/{id}/ForceDelete', 'PostsController@forceDelete')->name('blogs.forcedelete');

    //==================================================================================

    Route::get('/admin-panal/orders/{id}/restore', 'OrdersController@restore')->name('orders.restore');
    Route::get('/admin-panal/orders/get/trashed', 'OrdersController@getTrashed')->name('orders.trash');
    Route::get('/admin-panal/orders/{id}/ForceDelete', 'OrdersController@forceDelete')->name('orders.forcedelete');

    //===================================================================================

    Route::get('/admin-panal/sliders/{id}/restore', 'SliderController@restore')->name('sliders.restore');
    Route::get('/admin-panal/sliders/get/trashed', 'SliderController@getTrashed')->name('sliders.trash');
    Route::get('/admin-panal/sliders/{id}/ForceDelete', 'SliderController@ForceDelete')->name('sliders.forcedelete');

    Route::get('/MarkAllSeen', 'ContactsContoller@AllSeen');
    Route::get('/getcontactid/{image}/{subject}', 'ContactsContoller@GetContactId');

});

// ===================================================================================================================
// ===================================================================================================================

Route::group(['middleware' => ['web', 'lang']], function () {

    Route::get('/change/lang/{lang}', 'HomeController@langs')->middleware('auth');

    Route::get('/products/category/i/{category_id}/{category_name}', 'HomeController@getCategory')->name('products.category')->middleware('web');
    
    Route::get('/products/i/{id}/{name}', 'ProductsController@Product')->name('home.product')->middleware('web');

    // Ajax Requests
    Route::get('/ajax/products/information/', 'ProductsController@getAjaxProducts')->middleware('web');
    Route::get('/ajax/cart/create/', 'CartController@setAjaxCart');
    Route::get('/ajax/cart/removeProductFromCart/', 'CartController@removeProductFromCart');
    Route::get('/ajax/Wishlist/removeProductFromWishlist/', 'CartController@removeProductFromWishlist');

    Route::get('/ajax/cart/count/', 'CartController@setCartCount');
    Route::get('/ajax/cart/total/', 'CartController@getCartTotal');
    Route::get('/ajax/wishlist/content/', 'CartController@addToWishlist');
    Route::get('/ajax/wishlist/count/', 'CartController@getWishlistCount');
    Route::get('/ajax/cart/update/qty/', 'CartController@changeQty');
    Route::get('/ajax/moveToCart/', 'CartController@moveToCart');
    Route::get('/ajax/cart/showcartmodel/', 'CartController@getShowCartModel');
    
    // End Ajax Requests
    

    Route::post('/products/i/{id}/{name}', 'ProductsController@Review')->name('products')->middleware('auth');
    Route::post('/home/shopping-cart/checkout', 'OrdersController@store')->name('orders')->middleware('auth');

    
    Route::get('/products/filter/', 'ProductsController@GetFilter');
    Route::post('/products/filter/', 'ProductsController@FilterSorting')->middleware(['web', 'lang']);
    
    Route::view('/contact-us', 'site.pages.contact-us')->name('contact-us')->middleware('web');
    Route::post('/contact-us', 'ContactsContoller@store')->middleware('auth');
    
    Route::view('/about-us', 'site.pages.about-us')->name('about-us')->middleware('web');
    Route::view('/F&Qs', 'site.pages.faq')->name('faqs');
    Route::get('/shop', 'HomeController@Shop')->name('shop')->middleware('web');
    
    Route::get('/blog', 'PostsController@blog')->name('blog')->middleware('web');
    Route::get('/blog/i/{id}/{name}', 'PostsController@blogdetiles')->name('blog-details')->middleware('web');
    Route::post('/blog/i/{id}/{name}', 'PostsController@AddNewComment')->middleware('auth');

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home/shopping-cart', 'CartController@index')->name('cart.index')->middleware('auth');
    Route::post('/home/shopping-cart', 'CartController@store')->name('cart.store')->middleware('auth');
    Route::get('/home/profile/{username}', 'HomeController@profile')->name('home.profile')->middleware('auth');

    // Tags
    Route::get('/tags/colors/i/{id}/{color}', 'HomeController@ColorsTags');
    Route::get('/tags/products/i/{id}/{tag}', 'HomeController@ProductTags');
    Route::get('/tags/sizes/i/{id}/{size}', 'HomeController@SizesTags');
    Route::get('/tags/blog/i/{id}/{name}', 'HomeController@BlogsTags');

    Route::post('/cart/addToWishlist/', 'CartController@addToWishlist')->middleware('auth');
    
    Route::post('/home/users/PasswordChange', 'UsersController@UserChangePasssword');
    Route::get('/home/shopping-cart/checkout', 'CheckoutController@index')->name('checkout.index');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name'];

    public function post(){ $this->belongsToMany(Post::class)->withTimestamps(); }
    public function products(){ $this->belongsToMany(Product::class)->withTimestamps(); }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tag;

class TagsController extends Controller
{
    public function index()
    {
        $tags = Tag::all();
        return view('admin.tags.index', compact('tags'));
    }

    public function create()
    {
        return view('admin.tags.add');
    }

    public function store(Request $request)
    {
        Tag::create($request->all());
        return redirect()->back()->withFlashMessage('تم إضافة الكلمة الدلالية بنجاح');
    }

    public function edit($id)
    {
        $tag = Tag::find($id);
        return view('admin.tags.edit', compact('tag'));
    }

    public function update(Request $request, $id)
    {
        $tag = Tag::find($id)->update($request->name);
        return redirect()->back()->withFlashMessage('تم التعديل علي الكلمة الدلالية بنجاح');
    }

    public function destroy($id)
    {
        $tag = Tag::where('id', $id);
        
        DB::table('post_tag')->where('tag_id', $id)->delete();
        
        return redirect()->back()->withFlashMessage('تم حذف الكلمة الدلالية بنجاح');

    }
}

resources/views/admin/tags/add.blade.php
@extends('admin.layout.master') 
@section('title', 'إضافة كلمة دلالية') 
@section('content')
<div class="container">
    <div class="row">
        <section class="content-header">
            <h1 class="pull-right" dir="rtl">الكلمات الدلالية<small>إضافة الكلمة الدلالية</small></h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin-panal') }}"><i class="fa fa-dashboard"></i> الرئيسية</a></li>
                <li><a href="{{ route('tags.index') }}">الكلمات الدلالية</a></li>
                <li class="active">إضافة كلمة دلالية جديدة</li>
            </ol>
        </section>
        <div class="panel panel-default">
            <div class="panel-heading" dir="rtl">إضافة كلمة دلالية جديدة</div>
            <div class="panel-body">
                {!! Form::open(['route' => 'tags.store', 'method' => 'POST', 'dir' => 'rtl']) !!}
                    @include('admin.tags.form')
                    <div class="form-group row">
                        <input style="width: 150px;margin: 10px;" type="submit" name="submit" value="إضافة" class="btn btn-primary btn-lg">
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layout.master') 
@section('title', 'تعديل الكلمة الدلالية') 
@section('content')
<div class="container">
    <div class="row">
        <section class="content-header">
            <h1 class="pull-right" dir="rtl">الكلمات الدلالية<small>تعديل الكلمة الدلالية</small></h1>
            <ol class="breadcrumb">
                <li><a href="{{ route('admin-panal') }}"><i class="fa fa-dashboard"></i> الرئيسية</a></li>
                <li><a href="{{ route('tags.index') }}">الكلمات الدلالية</a></li>
                <li class="active">إضافة كلمة دلالية جديدة</li>
            </ol>
        </section>
        <div class="panel panel-default" dir="rtl">
            <div class="panel-heading h2">إضافة كلمة دلالية جديدة</div>
            <div class="panel-body">
                {!! Form::model($tag, ['route' => ['tags.update', $tag->id], 'method' => 'PATCH', 'style'=>'padding:20px;']) !!}
                    @include('admin.tags.form')
                    <div class="form-group row">
                        <input type="submit" name="submit" value="تعديل" class="btn btn-primary btn-lg">
                    </div> 
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tags/form.blade.php
{{-- Blog Tag Name --}}
<div class="form-group row">
    <label for="name" class="pull-right col-md-4 col-form-label text-md-right">{{ __('الاسم') }}</label>

    <div class="col-md-6 col-xs-12 pull-right">

        {!! Form::text("name", old('name'), ['class' => $errors->has('name') ? ' is-invalid form-control' : 'form-control', 'id'
        => 'name', 'required' => 'required']) !!} 
        @if ($errors->has('name'))<span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>@endif
    </div>
</div>

resources/views/admin/tags/index.blade.php
@extends('admin.layout.master') 
@section('title', 'الكلمات الدلالية') 
@section('content')
<div class="container">
    <div class="row">
        
        <section class="content-header">
            <h1 class="pull-right" dir="rtl">الكلمات الدلالية<small>عرض جميع الكلمات الدلالية</small></h1>
            <ol class="breadcrumb">
                <li class="h4"><a href="{{ route('admin-panal') }}"><i class="fa fa-dashboard"></i> الرئيسية</a></li>
                <li class="h4"><a href="{{ route('tags.index') }}">الكلمات الدلالية</a></li>
            </ol>
        </section>
        
        <br><br><br>
        
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header h4" dir="rtl">جدول الكلمات الدلالية</div>
                <div class="box-body">
                    <table class="table table-striped table-hover text-center">
                        <thead>
                            <tr>
                                <th>{{ __('#') }}</th>
                                <th>الاسم</th>
                                <th>تعديل/حذف</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($tags as $tag)
                            <tr>
                                <td>{{ $tag->id }}</td>
                                <td><h4>{{ $tag->name }}</h4></td>
                                <td>
                                    <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-success btn-lg">تعديل</a>
                                    <a href="{{ route('tags.destroy', $tag->id) }}" class="btn btn-danger btn-lg">حذف</a>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="3">
                                    <div class="text-center text-justify">{{ __('لا يوجد اي كلمات دلالية حالياً') }}</div>
                                </td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop